name: jeet
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.3
  date_time_picker: ^2.0.0
  dio: ^4.0.0
  easy_localization: ^3.0.0
  fluster: ^1.2.0
  flutter_bloc: ^7.0.1
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^4.1.2
  flutter_switch: ^0.3.1
  fluttertoast: ^8.0.7
  google_map_location_picker: ^4.1.7
  google_maps_flutter: ^2.0.6
  image_picker: ^0.7.5
  pin_code_text_field: ^1.8.0
  platform_date_picker: ^0.0.4+1
  provider: ^5.0.0
  queen_validators: ^0.2.3
  shared_preferences: ^2.0.6
  equatable: ^2.0.2
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lib/Resources/Translations/

  fonts:
    - family: dinnextl bold
      fonts:
        - asset: assets/fonts/ArbFONTS-DINNextLTArabic-Bold-2.ttf
    - family: dinnextl medium
      fonts:
        - asset: assets/fonts/ArbFONTS-DINNextLTArabic-Medium-2.ttf
    - family: dinnextl regular
      fonts:
        - asset: assets/fonts/ArbFONTS-DINNextLTArabic-Regular-2.ttf
